### ISSUE TITLE
Error: Cannot resolve module 'object-assign'

### ISSUE THREAD

**Issue by palibaacsi** [ryelle/Foxhound#1]
Hiya,

Very excited to see your theme, but getting an error when trying to install on a local vagrant instance. Everything seemed fine during install until during 'gulp' I got 5 errors:

    ERROR in ./js/stores/navigation-store.js
    ERROR in ./js/stores/posts-store.js
    ERROR in ./js/stores/term-store.js
    ERROR in ./js/stores/comments-store.js
    ERROR in ./js/dispatcher/dispatcher.js

each followed by: Module not found: Error: Cannot resolve module 'object-assign' in /Users

![foxhound errors](https://cloud.githubusercontent.com/assets/5721313/11750302/aa72df30-a000-11e5-81c2-2c8f760f5b0e.png)

**Comment by palibaacsi** [comment]
PS, same errors with Anadama, except only 4. No comments-store.js error.

**Comment by neurobotic** [comment]
+1
![screen shot 2015-12-11 at 1 30 39 pm](https://cloud.githubusercontent.com/assets/54392/11752082/8457e510-a00b-11e5-9bd5-5190f2d64821.png)

**Comment by ryelle** [comment]
I must've had it installed from a global package -- I've added it to the package.json file, so if you run `npm install` and `gulp` again, it should build for you.

**Comment by palibaacsi** [comment]
Looking great! Thanks, so much.
