### ISSUE TITLE
Jetpack compat?

### ISSUE THREAD

**Issue by ryelle** [ryelle/Foxhound#21]
I ❤ Jetpack and would like to keep likes, galleries, and stats working.

**Comment by ryelle** [comment]
Also really needs contact form styling. And..... functionality. It totally failed to submit - path is incorrect maybe?

**Comment by ryelle** [comment]
`wp_nonce_field` is used in the contact form to set a referrer, which is used to redirect after submission-- unfortunately this is pulled from the API, and is set to `/wp-json/wp/v2/pages?_embed=true&filter%5Bpagename%5D=[pagename]`. This is only used when a user is logged in, otherwise it redirects to the contact page (albeit with no success message). Acceptable functionality (for now).

**Comment by ryelle** [comment]
Stats -- can I reload the pixel via JS?

**Comment by jeherve** [comment]
I recently added the Related Posts to the REST API Post response. The patch will ship with the next version of Jetpack.
https://github.com/Automattic/jetpack/pull/3425

Here is an example of the elements added to each post:
https://jeremy.hu/wp-json/wp/v2/posts/18066

I think it'd be great to add those to your theme :)

![big_eyes_cat](https://cloud.githubusercontent.com/assets/426388/19811086/42c88b36-9d30-11e6-8a73-b957edd37219.png)
