### ISSUE TITLE
Links to category and tag archive pages don't seem to work

### ISSUE THREAD

**Issue by jeherve** [ryelle/Foxhound#28]
That seems to be an issue on your site as well: archive pages return all posts.
https://ryelle.codes/category/references/

**Comment by ryelle** [comment]
This seems to be due to the API team removing the `filter` param: https://github.com/WP-API/WP-API/issues/2799 and the JS library I use to fetch from the API relying on it. Looks like it's also a problem on date archives.

**Comment by ryelle** [comment]
This has been fixed in #31
