### ISSUE TITLE
Use create-react-app to automate the build

### ISSUE THREAD

**Issue by Olivia101** [ryelle/Foxhound#32]
Please consider using [create-react-app](https://github.com/facebookincubator/create-react-app) for building the JavaScript & CSS files.

**Comment by ryelle** [comment]
The JS and CSS are already build with webpack and babel, which are what create-react-app uses. Is there a specific feature from create-react-app you think this theme's build process needs?

**Comment by Olivia101** [comment]
It's a tool that myself and many other developers have been using and are familiar with and it's a tool that is fast evolving and growing very popular with the ReactJS community.

**Comment by ryelle** [comment]
I understand, I've used it before to start up small projects. But this project already exists, so I'm not sure what you're suggesting. If you'd like to see a specific technology from create-react-app brought in, please open another issue for that. Thanks!
