### ISSUE TITLE
Wordpress 4.7 REST API and GraphQL

### ISSUE THREAD

**Issue by Olivia101** [ryelle/Foxhound#33]
Assuming that the WP REST API Plugin is merged into WP 4.7 core, will the Foxhound theme be switched over to the WP API in core instead?

Also, do you have any plans to use [GraphQL](http://graphql.org/blog/rest-api-graphql-wrapper/) with the WP API in core?

**Comment by ryelle** [comment]
Yep! The theme already supported the WP core implementation of the API (the readme was just outdated, and has been updated).

I _probably_ won't move to GraphQL - I think this project is wrapping up, so I don't want to make any more API-level changes here.

**Comment by Olivia101** [comment]
Using the WP Rest API to fetch the data for the theme doesn't quite make sense as the WP Rest API is self consuming (the end points live on the same server I am serving the theme from) and I can save myself the round trip requests from the browser to the server and then back down to the browser again. 
This is where GraphQL could cut down the number of data requests.
Thank you for sharing your hard work. Much appreciated. 
Hopefully you will change your mind about GraphQL!

**Comment by ryelle** [comment]
> I can save myself the round trip requests from the browser to the server

This is true, but in this case we're saving time by a) preloading the initial page of data which is returned from the server when the page loads, and b) we're _only_ fetching the API data on subsequent page views, so the server doesn't have to render the entire page + asset requests again.

**Comment by Olivia101** [comment]
This [GraphQL endpoint for WordPress](https://github.com/tim-field/graphql-wp) looks like a great project.
