### ISSUE TITLE
Placeholder or loading message

### ISSUE THREAD

**Issue by ryelle** [ryelle/Foxhound#5]
While the API request fetches, we can display a loading message or placeholder.

Currently a generic loading message:

![screen shot 2016-09-03 at 1 10 51 pm](https://cloud.githubusercontent.com/assets/541093/18226437/e5af20d2-71d7-11e6-8979-d70ddd80b90c.png)

**Comment by melchoyce** [comment]
Maybe instead of "Your posts are loading," we say "Posts incoming ..." and use the `&hellip;` entity. Or, we could animate the . . . in and out while the posts load, like:

.
..
...
..
.
etc.

**Comment by melchoyce** [comment]
Might also look nice italic.

**Comment by ryelle** [comment]
Condensed all the placeholder displays into one `Placeholder` component.

Also tried an animation that looks kind of ridiculous for the index screen, but once #16's implemented we shouldn't need that.

**Comment by ryelle** [comment]
Animation's been killed, looks weird with preloading. Considering this done.
