### ISSUE TITLE
Color contrast on link border in content

### ISSUE THREAD

**Issue by ryelle** [ryelle/Foxhound#78]
From review:

> I should have caught this on the first review, but the underline color (presented via shadow) on content links doesn't meet contrast requirements. An underlined link avoids contrast requirements for links, *but* the underline needs to itself be visible. The underline being at #dddfde gives a 1.34:1 contrast. I think you could get away with as low as 3:1; it's not text, so it's hard to judge it according to text size standards, but 1.34:1 is too low. 

[Here's the current color & background in tanaguru's color contrast tool](http://contrast-finder.tanaguru.com/result.html?foreground=%23DDDFDE&background=%23FCFBF8&ratio=3&isBackgroundTested=false&algo=HSV)

@melchoyce I tried a few colors from the above link:

https://cloudup.com/idvl74cZMvC

**Comment by melchoyce** [comment]
I like `#929294` and `#829494` best.
