### ISSUE TITLE
TypeError in app.js

### ISSUE THREAD

**Issue by Rarst** [ryelle/Foxhound#82]
Getting following error in console:

> Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined app,js?ver=1.0.3

Windows 7, Chrome 56.0.2924.87

**Comment by ryelle** [comment]
Are you getting this on a site you've installed foxhound on, or on the wp-themes.com demo?

**Comment by Rarst** [comment]
On my local WP dev install.

**Comment by ryelle** [comment]
Thanks for reporting this. Looks like it came from not having a menu defined. I've fixed the code here, but I'm going to wait a bit before submitting another version to wp.org.
